
References
==========

Bivand, R., & Gebhardt, A. (2000). Implementing functions for spatial
statistical analysis using the R language. Journal of Geographical
Systems, 2(3), 307–317.

Bivand, R. S., Pebesma, E. J., & Rubio, V. G. (2013). Applied spatial
data: analysis with R. Springer.

Burrough, P. A. & McDonnell, R. A. (1998). Principals of Geographic
Information Systems (revised edition). Clarendon Press, Oxford.

Goodchild, M. F. (2007). Citizens as sensors: the world of volunteered
geography. GeoJournal, 69(4), 211–221.

Harris, R. (2012). A Short Introduction to R.
[social-statistics.org](http://www.social-statistics.org/).

Kabacoff, R. (2011). R in Action. Manning Publications Co.

Krygier, J. Wood, D. 2011. Making Maps: A Visual Guide to Map Design for
GIS (2nd Ed.). New York: The Guildford Press.

Longley, P., Goodchild, M. F., Maguire, D. J., & Rhind, D. W. (2005).
Geographic information systems and science. John Wiley & Sons.

Monkhouse, F.J. and Wilkinson, H. R. 1973. Maps and Diagrams Their Compilation and Construction (3rd Edition, reprinted with revisions). London: Methuen & Co Ltd. 

Ramsey, P., & Dubovsky, D. (2013). Geospatial Software's Open Future.
GeoInformatics, 16(4).

Sherman, G. (2008). Desktop GIS: Mapping the Planet with Open Source
Tools. Pragmatic Bookshelf.

Torfs and Brauer (2012). A (very) short Introduction to R. The
Comprehensive R Archive Network.

Venables, W. N., Smith, D. M., & Team, R. D. C. (2013). An introduction
to R. The Comprehensive R Archive Network (CRAN). Retrieved from
http://cran.ma.imperial.ac.uk/doc/manuals/r-devel/R-intro.pdf .

Wickham, H. (2009). ggplot2: elegant graphics for data analysis.
Springer.

Wickham, H. 2010. A Layered Grammar of Graphics. American Statistical Association, Institute of Mathematics Statistics and Interface Foundation of North America Journal of Computational and Graphical Statistics. 19, 1: 3-28

Endnotes
=======

1. "What kind of a name is R?" common question. R's
    name originates from the creators of R, Ross Ihaka and Robert
    Gentleman. R is an open source implementation of the statistical
    programming language S, so its name is also a play on words that
    makes implicit reference to this.

2. R is notoriously difficult to search for on major search engines, as
    it is such a common letter with many other uses beyond the name of a
    statistical programming language. This should not be a deterrent, as
    R has a wealth of excellent online resources. To overcome the issue,
    you can either be more specific with the search term (e.g. "R
    spatial statistics") or use an R specific search engine such as
    [rseek.org](http://www.rseek.org/). You can also search of online
    help *from within R* using the command `RSiteSearch`. E.g.
    `RSiteSearch("spatial statistics")`. Experiment and see which you
    prefer!
    
3. The file was downloaded using the following command: 
    "download.file("http://www.openstreetmap.org/trace/1619756/data", destfile = "data/gps-trace.gpx")".
    More information about this ride, and a
    [video](http://www.youtube.com/watch?v=6a8QLiC4LV8&feature=share)
    from it, can be found on
    [robinlovelace.net](http://robinlovelace.net/ecotech/2013/10/13/bicycle-trailer-move.html).
    
4. A complete list of drivers for importing and exporting spatial data can 
    be displayed by typing `getGDALDriverNames()`.
    
5. Slots are elements found 'inside' classes of the 
    [S4 object system](http://adv-r.had.co.nz/S4.html). 
    While the sub-elements of S3 objects such as `data.frame` are referred to 
    using the `$` symbol, the slots of S4 objects are identified using `@`.
    Thus, the variable `x` of dataframe `df` can be referred to with `df$x`.
    In the same way, the data associated with a polygon layer such as `lnd` can 
    be accessed with `lnd@data`. Note that `lnd@data` is itself a dataframe, 
    so can be further specified, e.g. with `lnd@data$name`. For more on spatial 
    data classes, see Bivand et al. (2013).
    
6. EPSG stands for "European Petroleum Survey Group", but this is not really worth 
    knowing as the organisation is now defunct ([www.epsg.org/](http://www.epsg.org/)).
    The important thing is that EPSG codes provide a unified way to refer to a 
    wide range of coordinate systems, as each CRS has its own epsg code. 
    These can be found at the website [spatialreference.org](http://spatialreference.org/).
    To see how this website can be useful, try searching for "osgb", for example to 
    find the epsg code for the British National Grid.
    
7. To see how the `crimeAg` dataset was created, please refer to the 
    "Creating-maps-in-R" tutorial (Cheshire and Lovelace, 2014) hosted 
    on [GitHub](https://github.com/Robinlovelace/Creating-maps-in-R). 
    The file 
    "[intro-spatial-rl.pdf](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/intro-spatial-rl.pdf)" 
    contains this information, 
    in the section on "Downloading addtional data". 
    
```{r}
source("md2pdf.R") # convert chapter to tex
```
