A Final Example
===============

```{r, echo=FALSE, message=FALSE}
library(rgdal)
```

  
  Here we present a final example that draws upon the many advanced concepts discussed in this chapter to produce a map of 18th Century Shipping flows. 

```{r}
library(ggplot2)
library(png)
wrld <- readOGR("data", "data/ne_110m_admin_0_countries")
btitle<-readPNG("figure/brit_titles.png")
compass<-readPNG("figure/windrose.png")
earth<-readPNG("figure/earth_raster.png")
bdata<-read.csv("data/british_shipping_example.csv")

```

```{r}
xquiet<- scale_x_continuous("", breaks=NULL)
yquiet<-scale_y_continuous("", breaks=NULL)
quiet<-list(xquiet, yquiet)
```

```{r}
wrld.f<-fortify(wrld, region="sov_a3")
base<- ggplot(wrld.f, aes(x = long, y = lat))
```

```{r}
route<-c(geom_path(aes(long,lat,group=paste(bdata$trp, bdata$group.regroup, sep=".")), colour="#0F3B5F", size=0.2, data= bdata, alpha=0.5, lineend="round")) 
```

```{r}
wrld<-c(geom_polygon(aes(group=group), size = 0.1, colour= "black", fill="#D6BF86", data=wrld.f, alpha=1))
```

```{r}
base+route+wrld + theme(panel.background = element_rect(fill='#BAC4B9',colour='black')) +annotation_raster(btitle, xmin = 30, xmax = 140, ymin = 51, ymax = 87)+annotation_raster(compass, xmin = 65, xmax = 105, ymin = 25, ymax = 65)+ coord_equal()+quiet
```


```{r}
base+annotation_raster(earth, xmin = -180, xmax = 180, ymin = -90, ymax = 90)+route+ theme(panel.background = element_rect(fill='#BAC4B9',colour='black')) +annotation_raster(btitle, xmin = 30, xmax = 140, ymin = 51, ymax = 87)+annotation_raster(compass, xmin = 65, xmax = 105, ymin = 25, ymax = 65)+ coord_equal()+quiet
```
!!!change the colour of the routes to make them stand out more.

Animating your plots

```{r}
ani.record(reset = TRUE)
  for (i in unique(bdata$year))
    {
    route<-c(geom_path(aes(long,lat,group=paste(trp, group.regroup, sep=".")), colour="#0F3B5F", size=0.2, data= bdata[which(bdata$year==i),], alpha=0.5, lineend="round"))
    print(base+route+wrld + theme(panel.background = element_rect(fill='#BAC4B9',colour='black')) +annotation_raster(btitle, xmin = 30, xmax = 140, ymin = 51, ymax = 87)+annotation_raster(compass, xmin = 65, xmax = 105, ymin = 25, ymax = 65)+ coord_equal()+quiet+ggtitle(i))
ani.record()
    dev.off()
    }  
```


saveHTML(ani.replay(), img.name = "record_plot",outdir = getwd())


Recap and Conclusions
=====================